### ISSUE TITLE
Camden SR5 Kafka versions for Spring Cloud Stream don't work with Spring Boot 1.5.1

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [spring-cloud/spring-cloud-release#70]
I hope this is the correct repository to open this report.

I updated a project that used Spring Boot 1.4.4.RELEASE and Spring Cloud Camden SR4 to Spring Boot 1.5.1.RELEASE and Spring Cloud Camden SR5.

The project uses Spring Cloud Dataflow with Kafka bindings. With the updated versions microservices that read from Kafka don't boot anymore because the version of `spring-kafka` is not compatible with the version of `spring-integration-kafka`.

This is the exception at startup:
```
Caused by: java.lang.NoSuchMethodError: org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.<init>(Ljava/lang/reflect/Method;)V
```

A solution is to manually use `spring-kafka:1.0.3.RELEASE` instead of `spring-kafka:1.1.2.RELEASE`.

Maybe I'm also using the POMs wrong? I import `spring-cloud-dependencies` and `spring-boot-dependencies` but don't use any Spring parent POM.

Here is a sample Maven project where the application does not start because of the error above.
[sp-kafka-versions.zip](https://github.com/spring-cloud/spring-cloud-release/files/754872/sp-kafka-versions.zip)

**Comment by spencergibb** [comment]
@mbogoevici I believe, has the proper procedure.

**Comment by FrontierPsychiatrist** [comment]
Any news on this?

**Comment by spencergibb** [comment]
ping @mbogoevici

**Comment by mbogoevici** [comment]
@FrontierPsychiatrist Sorry for missing this: unfortunately this is caused Spring Boot 1.5.1 partly overriding the dependency set of the binder. 

You have two options here: either to upgrade the version of Spring Integration Kafka to 2.1.0 and bring it inline with the rest of the Spring Boot dependency set, or downgrading the Spring Kafka version as you did.

Using Dalston would bring a consistent dependency set.

**Comment by spencergibb** [comment]
@mbogoevici I wonder if this should be in some release notes somewhere?

**Comment by mbogoevici** [comment]
Yes. It is a newly discovered issue, unfortunately.

**Comment by FrontierPsychiatrist** [comment]
Thank you for the comments! I guess for now doing the manual upgrade works for me. Since @mbogoevici opened another ticket I will close this one.
